import type { PortfolioData } from '../../types/portfolio';

const asset = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`;

export const portfolioData: PortfolioData = {
  socialLinks: [
    { id: 'github', labelKey: 'social.github', url: 'https://github.com/JRaamos' },
    {
      id: 'linkedin',
      labelKey: 'social.linkedin',
      url: 'https://www.linkedin.com/in/jonathan-febraio/',
    },
    { id: 'email', labelKey: 'social.email', url: 'mailto:jhonyramos46@gmail.com' },
  ],
  projects: [
    {
      id: 'febraioTech',
      categoryKey: 'projects.febraioTech.category',
      titleKey: 'projects.febraioTech.title',
      descriptionKey: 'projects.febraioTech.description',
      problemKey: 'projects.febraioTech.problem',
      roleKey: 'projects.febraioTech.role',
      architectureKey: 'projects.febraioTech.architecture',
      decisionsKey: 'projects.febraioTech.decisions',
      qualityKey: 'projects.febraioTech.quality',
      deploymentKey: 'projects.febraioTech.deployment',
      image: asset('projects/febraio-tech.png'),
      imageAltKey: 'projects.febraioTech.imageAlt',
      tags: ['TypeScript', 'Next.js', 'Medusa v2', 'PostgreSQL', 'Docker'],
      liveUrl: 'https://www.febraiotech.com.br/',
      accessKey: 'projects.privateSource',
      featured: true,
    },
    {
      id: 'manualDosAchados',
      categoryKey: 'projects.manualDosAchados.category',
      titleKey: 'projects.manualDosAchados.title',
      descriptionKey: 'projects.manualDosAchados.description',
      problemKey: 'projects.manualDosAchados.problem',
      roleKey: 'projects.manualDosAchados.role',
      architectureKey: 'projects.manualDosAchados.architecture',
      decisionsKey: 'projects.manualDosAchados.decisions',
      qualityKey: 'projects.manualDosAchados.quality',
      deploymentKey: 'projects.manualDosAchados.deployment',
      image: asset('projects/manual-dos-achados.png'),
      imageAltKey: 'projects.manualDosAchados.imageAlt',
      tags: ['Next.js', 'React', 'Strapi 5', 'PostgreSQL', 'SEO workflows'],
      liveUrl: 'https://www.manualdosachados.com.br/',
      sourceUrl: 'https://github.com/JRaamos/guide-to-findings-front-end',
      featured: true,
    },
    {
      id: 'cryptoAi',
      categoryKey: 'projects.cryptoAi.category',
      titleKey: 'projects.cryptoAi.title',
      descriptionKey: 'projects.cryptoAi.description',
      problemKey: 'projects.cryptoAi.problem',
      roleKey: 'projects.cryptoAi.role',
      architectureKey: 'projects.cryptoAi.architecture',
      decisionsKey: 'projects.cryptoAi.decisions',
      qualityKey: 'projects.cryptoAi.quality',
      deploymentKey: 'projects.cryptoAi.deployment',
      image: asset('projects/crypto-ai.png'),
      imageAltKey: 'projects.cryptoAi.imageAlt',
      tags: ['React', 'Express', 'Prisma', 'OpenAI API', 'Zod'],
      accessKey: 'projects.privateSource',
      featured: true,
    },
    {
      id: 'buildBalance',
      categoryKey: 'projects.buildBalance.category',
      titleKey: 'projects.buildBalance.title',
      descriptionKey: 'projects.buildBalance.description',
      problemKey: 'projects.buildBalance.problem',
      roleKey: 'projects.buildBalance.role',
      architectureKey: 'projects.buildBalance.architecture',
      decisionsKey: 'projects.buildBalance.decisions',
      qualityKey: 'projects.buildBalance.quality',
      deploymentKey: 'projects.buildBalance.deployment',
      image: asset('projects/buildbalance.png'),
      imageAltKey: 'projects.buildBalance.imageAlt',
      tags: ['NestJS', 'Prisma', 'PostgreSQL', 'React', 'Redux Toolkit'],
      sourceUrl: 'https://github.com/JRaamos/BuildBalance',
    },
    {
      id: 'converseComAmor',
      categoryKey: 'projects.converseComAmor.category',
      titleKey: 'projects.converseComAmor.title',
      descriptionKey: 'projects.converseComAmor.description',
      problemKey: 'projects.converseComAmor.problem',
      roleKey: 'projects.converseComAmor.role',
      architectureKey: 'projects.converseComAmor.architecture',
      decisionsKey: 'projects.converseComAmor.decisions',
      qualityKey: 'projects.converseComAmor.quality',
      deploymentKey: 'projects.converseComAmor.deployment',
      image: asset('projects/converse-com-amor.png'),
      imageAltKey: 'projects.converseComAmor.imageAlt',
      tags: ['Next.js', 'React', 'TypeScript', 'Supabase', 'Playwright'],
      sourceUrl: 'https://github.com/JRaamos/Converse-com-amor',
    },
  ],
  experiences: [
    {
      id: 'xapps',
      periodKey: 'experience.xapps.period',
      roleKey: 'experience.xapps.role',
      companyKey: 'experience.xapps.company',
      descriptionKey: 'experience.xapps.description',
      tags: ['React', 'React Native', 'TypeScript', 'REST APIs', 'CI/CD'],
    },
    {
      id: 'independent',
      periodKey: 'experience.independent.period',
      roleKey: 'experience.independent.role',
      companyKey: 'experience.independent.company',
      descriptionKey: 'experience.independent.description',
      tags: ['TypeScript', 'Node.js', 'React', 'PostgreSQL', 'Docker'],
    },
    {
      id: 'trybe',
      periodKey: 'experience.trybe.period',
      roleKey: 'experience.trybe.role',
      companyKey: 'experience.trybe.company',
      descriptionKey: 'experience.trybe.description',
      tags: ['Technical Mentoring', 'JavaScript', 'TypeScript', 'React', 'Node.js'],
    },
  ],
  skillGroups: [
    {
      id: 'fullstack',
      titleKey: 'skills.fullstack',
      descriptionKey: 'skills.fullstackDescription',
      skills: ['TypeScript', 'JavaScript', 'React', 'Next.js', 'Node.js'],
    },
    {
      id: 'backend',
      titleKey: 'skills.backend',
      descriptionKey: 'skills.backendDescription',
      skills: ['NestJS', 'Express', 'REST APIs', 'PostgreSQL', 'Prisma'],
    },
    {
      id: 'mobile',
      titleKey: 'skills.mobile',
      descriptionKey: 'skills.mobileDescription',
      skills: ['React Native', 'Expo', 'iOS', 'Android', 'EAS'],
    },
    {
      id: 'delivery',
      titleKey: 'skills.delivery',
      descriptionKey: 'skills.deliveryDescription',
      skills: ['Docker', 'CI/CD', 'AWS', 'Jest', 'Vitest', 'Playwright'],
    },
  ],
};
