import type { PortfolioData } from '../../types/portfolio';

export const portfolioData: PortfolioData = {
  socialLinks: [
    { id: 'github', labelKey: 'social.github', url: 'https://github.com/jonathanfebraio' },
    {
      id: 'linkedin',
      labelKey: 'social.linkedin',
      url: 'https://www.linkedin.com/in/jonathanfebraio/',
    },
    { id: 'twitter', labelKey: 'social.twitter', url: 'https://x.com/jonathanfebraio' },
    { id: 'email', labelKey: 'social.email', url: 'mailto:jonathan@febraio.com.br' },
  ],
  projects: [
    {
      id: 'nexus',
      categoryKey: 'projects.nexus.category',
      titleKey: 'projects.nexus.title',
      descriptionKey: 'projects.nexus.description',
      tags: ['Rust', 'React', 'Redis', 'PostgreSQL'],
      visual: 'blue',
    },
    {
      id: 'orbital',
      categoryKey: 'projects.orbital.category',
      titleKey: 'projects.orbital.title',
      descriptionKey: 'projects.orbital.description',
      tags: ['Python', 'FastAPI', 'TypeScript', 'OpenAI'],
      visual: 'indigo',
    },
    {
      id: 'vanta',
      categoryKey: 'projects.vanta.category',
      titleKey: 'projects.vanta.title',
      descriptionKey: 'projects.vanta.description',
      tags: ['Next.js', 'Prisma', 'TimescaleDB', 'D3.js'],
      visual: 'green',
      featured: true,
    },
    {
      id: 'helix',
      categoryKey: 'projects.helix.category',
      titleKey: 'projects.helix.title',
      descriptionKey: 'projects.helix.description',
      tags: ['Go', 'Rust', 'WASM', 'Lua'],
      visual: 'red',
    },
    {
      id: 'flare',
      categoryKey: 'projects.flare.category',
      titleKey: 'projects.flare.title',
      descriptionKey: 'projects.flare.description',
      tags: ['Rust', 'V8', 'WASM', 'TypeScript'],
      visual: 'amber',
    },
    {
      id: 'prism',
      categoryKey: 'projects.prism.category',
      titleKey: 'projects.prism.title',
      descriptionKey: 'projects.prism.description',
      tags: ['Go', 'React', 'D3.js', 'Terraform'],
      visual: 'cyan',
    },
  ],
  experiences: [
    {
      id: 'founder',
      periodKey: 'experience.founder.period',
      roleKey: 'experience.founder.role',
      companyKey: 'experience.founder.company',
      descriptionKey: 'experience.founder.description',
      tags: ['React', 'Node.js', 'PostgreSQL', 'AWS', 'Leadership'],
    },
    {
      id: 'senior',
      periodKey: 'experience.senior.period',
      roleKey: 'experience.senior.role',
      companyKey: 'experience.senior.company',
      descriptionKey: 'experience.senior.description',
      tags: ['TypeScript', 'Node.js', 'React', 'Docker', 'Redis'],
    },
    {
      id: 'fullstack',
      periodKey: 'experience.fullstack.period',
      roleKey: 'experience.fullstack.role',
      companyKey: 'experience.fullstack.company',
      descriptionKey: 'experience.fullstack.description',
      tags: ['React', 'PHP', 'MySQL', 'JavaScript', 'REST APIs'],
    },
    {
      id: 'freelance',
      periodKey: 'experience.freelance.period',
      roleKey: 'experience.freelance.role',
      companyKey: 'experience.freelance.company',
      descriptionKey: 'experience.freelance.description',
      tags: ['HTML', 'CSS', 'JavaScript', 'WordPress', 'PHP'],
    },
  ],
  skillGroups: [
    {
      id: 'fullstack',
      titleKey: 'skills.fullstack',
      skills: ['TypeScript', 'JavaScript', 'Python', 'Go'],
      proficiency: 96,
    },
    {
      id: 'architecture',
      titleKey: 'skills.architecture',
      skills: ['React', 'Next.js', 'Node.js', 'GraphQL'],
      proficiency: 90,
    },
    {
      id: 'devops',
      titleKey: 'skills.devops',
      skills: ['Docker', 'AWS', 'CI/CD', 'Observability'],
      proficiency: 84,
    },
    {
      id: 'distributed',
      titleKey: 'skills.distributed',
      skills: ['PostgreSQL', 'Redis', 'Docker', 'AWS'],
      proficiency: 87,
    },
    {
      id: 'frontendFocus',
      titleKey: 'skills.frontendFocus',
      skills: ['React', 'Design Systems', 'Accessibility', 'Motion'],
      proficiency: 88,
    },
    {
      id: 'integrations',
      titleKey: 'skills.integrations',
      skills: ['REST', 'GraphQL', 'Webhooks', 'Payments'],
      proficiency: 93,
    },
  ],
  articles: [
    {
      id: 'typescript',
      categoryKey: 'writing.typescript.category',
      dateKey: 'writing.typescript.date',
      titleKey: 'writing.typescript.title',
      descriptionKey: 'writing.typescript.description',
      durationKey: 'writing.typescript.duration',
    },
    {
      id: 'consistency',
      categoryKey: 'writing.consistency.category',
      dateKey: 'writing.consistency.date',
      titleKey: 'writing.consistency.title',
      descriptionKey: 'writing.consistency.description',
      durationKey: 'writing.consistency.duration',
    },
    {
      id: 'coldstart',
      categoryKey: 'writing.coldstart.category',
      dateKey: 'writing.coldstart.date',
      titleKey: 'writing.coldstart.title',
      descriptionKey: 'writing.coldstart.description',
      durationKey: 'writing.coldstart.duration',
    },
  ],
};
